apiVersion: v1
kind: Service
metadata:
  name: assessment-service
  namespace: assessment 
spec:
  selector:
    app: node
  # type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
